# AUTOGENERATED BY optimize_weights.py - DO NOT EDIT MANUALLY
MOVE_SCORE_WEIGHTS = {
    "pv_bonus": 1.29,
    "killer_0_bonus": 2.096,
    "killer_1_bonus": 0.709,
    "quiet_history_scale": 2.60,
    "counter_move_scale": 1.42,
    "capture_history_scale": 4.05,
    "see_scale": 2.102,
}
