import optuna
import subprocess
import time
from typing import Optional
import sys

WEIGHT_FILE = "weights.py"


import subprocess
import time
from typing import Optional

def run_engine_and_get_node_count() -> float:
    process: Optional[subprocess.Popen] = None
    node_count_5 = float('inf')
    node_count_6 = float('inf')

    def send(cmd: str) -> None:
        try:
            if process and process.stdin:
                process.stdin.write(cmd + "\n")
                process.stdin.flush()
        except Exception as e:
            print(f"⚠️ send() failed for '{cmd}': {e}")

    def read_until(keyword: str, timeout: float = 10.0) -> str:
        start = time.time()
        while time.time() - start < timeout:
            if process and process.stdout:
                line = process.stdout.readline()
                if not line:
                    continue
                print("[ENGINE]", line.strip())  # voit poistaa tämän jos ei tarvitse debuggaukseen
                if keyword in line:
                    return line
        raise TimeoutError(f"⏰ Timeout waiting for '{keyword}'")

    try:
        process = subprocess.Popen(
            [sys.executable, "-u", "main.py"],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            bufsize=1
        )

        if not process.stdin or not process.stdout:
            raise RuntimeError("❌ stdin or stdout is None")

        send("uci")
        read_until("uciok")

        send("isready")
        read_until("readyok")

        send("position startpos")
        send("go depth 6")

        while True:
            if not process.stdout:
                break
            line = process.stdout.readline()
            if not line:
                break

            print("[ENGINE]", line.strip())  # voit poistaa tämän jos ei tarvitse debuggaukseen

            if "info depth 5" in line and "nodes" in line:
                parts = line.split()
                if "nodes" in parts:
                    try:
                        node_count_5 = int(parts[parts.index("nodes") + 1])
                    except Exception as e:
                        print("⚠️ Parsing error:", e)
            
            if "info depth 6" in line and "nodes" in line:
                parts = line.split()
                if "nodes" in parts:
                    try:
                        node_count_6 = int(parts[parts.index("nodes") + 1])
                    except Exception as e:
                        print("⚠️ Parsing error:", e)

            if line.startswith("bestmove"):
                break

        send("quit")
        try:
            process.wait(timeout=5)
        except subprocess.TimeoutExpired:
            print("⏳ Engine did not exit in time, killing process.")
            process.kill()

        # stderr-tarkistus
        if process.stderr:
            errors = process.stderr.read()
            if errors:
                print("[ENGINE STDERR]", errors)

    except subprocess.TimeoutExpired:
        print("⏰ Timeout: engine took too long.")
        if process:
            process.kill()
    except TimeoutError as e:
        print(str(e))
        if process:
            try:
                send("quit")
                process.wait(timeout=5)
            except Exception:
                process.kill()
    except Exception as e:
        print(f"❌ Unexpected error in subprocess: {e}")
        if process:
            process.kill()

    return node_count_5 + node_count_6




def write_weights_to_file(weights_dict):
    with open(WEIGHT_FILE, "w") as f:
        f.write("# AUTOGENERATED BY optimize_weights.py - DO NOT EDIT MANUALLY\n")
        f.write("MOVE_SCORE_WEIGHTS = {\n")
        for key, val in weights_dict.items():
            f.write(f"    \"{key}\": {val:.6f},\n")
        f.write("}\n")

def objective(trial):
    weights = {
        "pv_bonus": trial.suggest_float("pv_bonus", 1.28, 1.30),
        "killer_0_bonus": trial.suggest_float("killer_0_bonus", 2.04, 2.25),
        "killer_1_bonus": trial.suggest_float("killer_1_bonus", 0.7, 0.72),
        "quiet_history_scale": trial.suggest_float("quiet_history_scale", 2.58, 2.62),
        "counter_move_scale": trial.suggest_float("counter_move_scale", 1.41, 1.43),
        "capture_history_scale": trial.suggest_float("capture_history_scale", 4.02, 4.09),
        "see_scale": trial.suggest_float("see_scale", 2.09, 2.11),
    }

    write_weights_to_file(weights)
    node_count = run_engine_and_get_node_count()
    return node_count

if __name__ == "__main__":
    study = optuna.create_study(direction="minimize")
    study.optimize(objective, n_trials=1000)

    print("Paras painotus:", study.best_params)
    print("Pienin node count:", study.best_value)
